
all:
	cd shadow_sample/                               && $(MAKE) all
	cd jobs_sample/                                 && $(MAKE) all
	cd subscribe_publish_sample/                    && $(MAKE) all
	cd sensor2cloud-aws/                            && $(MAKE) all

clean:
	cd shadow_sample/                               && $(MAKE) clean
	cd jobs_sample/                                 && $(MAKE) clean
	cd subscribe_publish_sample/                    && $(MAKE) clean
	cd sensor2cloud-aws/                            && $(MAKE) clean
